server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  security:
    #user:
    #  name: admin
    #user:
    #  password: q1w2e3
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api
            client-secret: api
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            authorization-uri: http://192.168.25.157:9080/auth/realms/demo/protocol/openid-connect/auth
            token-uri: http://192.168.25.157:9080/auth/realms/demo/protocol/openid-connect/token
            user-info-uri: http://192.168.25.157:9080/auth/realms/demo/protocol/openid-connect/userinfo
            jwk-set-uri: http://192.168.25.157:9080/auth/realms/demo/protocol/openid-connect/certs
            user-name-attribute: preferred_username
